from state import get_state, update_state
from state_management import graph
from dotenv import load_dotenv
load_dotenv()
import os
import threading
from redis_checkpoint import enqueue_payload, get_next_payload
from utils.mr_write import build_confluence_link,post_comment_to_mr

import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger(__name__)

_worker_thread = None
_worker_lock = threading.Lock()

# ─── Worker ───────────────────────────────────────────────────────────────────

def _process(payload: dict):
    project     = payload.get("project", {})
    obj_attrs   = payload.get("object_attributes", {})
    last_commit = obj_attrs.get("last_commit", {})
    project_id  = project.get("id")

    logger.info(f"Processing | project={project.get('name')} | MR={obj_attrs.get('iid')}")

    update_state(
        project_name          = project.get("name"),
        project_id            = project_id,
        git_http_url          = project.get("git_http_url"),
        branch                = obj_attrs.get("target_branch"),
        iid                   = obj_attrs.get("iid"),
        mr_url                = obj_attrs.get("url"),
        merge_commit_sha      = obj_attrs.get("merge_commit_sha"),
        last_commit_id        = last_commit.get("id"),
        gitlab_base_url       = os.getenv("GITLAB_BASE_URL"),
        git_token             = os.getenv("GIT_TOKEN"),
        confluence_token      = os.getenv("CONFLUENCE_TOKEN"),
        project_page_id       = os.getenv("PROJECT_PARENT"),
        release_notes_page_id = os.getenv("RELEASENOTES_PARENT"),
        space_key             = os.getenv("SPACE_KEY"),
    )

    state = get_state(project_id)
    result = graph.invoke(state)
    
    prj_child_page_id = result.get("prj_child_page_id")
    rn_child_page_id = result.get("rn_child_page_id")

    project_link = build_confluence_link(prj_child_page_id)
    release_link = build_confluence_link(rn_child_page_id)

    message = f"""Confluence Documentation Created
    <br>
    <b>Project Documentation</b>
    {project_link}
    <br>
    <b>Release Notes</b>
    {release_link}
    <br>
    ---
    <b>**Auto-generated by workflow**</b>
    """
    project_id = project.get("id")
    base_url = os.getenv("GITLAB_BASE_URL")
    token = os.getenv("GIT_TOKEN")
    iid = obj_attrs.get("iid")
    post_comment_to_mr(base_url,project_id,token,iid, message)
    
    logger.info(f"Done | project={project.get('name')} | MR={obj_attrs.get('iid')}")


def run_worker():
    logger.info("Worker started, waiting for payloads...")
    while True:
        try:
            payload = get_next_payload()
            if payload is None:
                continue
            project = payload.get("project", {})
            obj_attrs = payload.get("object_attributes", {})
            logger.info(
                f"Dequeued payload | project={project.get('name')} | MR={obj_attrs.get('iid')}"
            )
            _process(payload)
        except Exception as e:
            logger.error(f"Worker error: {e}", exc_info=True)


def start_worker_thread():
    global _worker_thread

    with _worker_lock:
        if _worker_thread and _worker_thread.is_alive():
            logger.info("Worker thread already running")
            return _worker_thread

        _worker_thread = threading.Thread(target=run_worker, daemon=True, name="webhook-worker")
        _worker_thread.start()
        logger.info("Worker thread started")
        return _worker_thread


# ─── Webhook Handler ──────────────────────────────────────────────────────────

def process_webhook(payload: dict):
    object_kind   = payload.get("object_kind")
    event_type    = payload.get("event_type")
    project       = payload.get("project", {})
    obj_attrs     = payload.get("object_attributes", {})
    state_val     = obj_attrs.get("state")
    target_branch = obj_attrs.get("target_branch")
    merge_status  = obj_attrs.get("merge_status")

    is_merge_request  = object_kind == "merge_request" and event_type == "merge_request"
    is_merged_to_main = state_val == "merged" and target_branch == "main"

    logger.info(
        f"Webhook received | project={project.get('name')} | "
        f"state={state_val} | target={target_branch} | merge_status={merge_status}"
    )

    if is_merge_request and is_merged_to_main:
        iid          = obj_attrs.get("iid")
        merge_commit = obj_attrs.get("merge_commit_sha")

        logger.info(f"Enqueueing | project={project.get('name')} | MR={iid}")

        start_worker_thread()
        enqueue_payload(payload)
        
        message = f"""Confluence Documentation Generation Initiated
            <br>
            <b>Project Documentation</b>
            Generating
            <br>
            <b>Release Notes</b>
            Generating
            <br>
            <br>
            Pages will be generated and links will be populated after the workflow complete!
            ---
            <b>**Auto-generated by workflow**</b>
            """
        project_id = project.get("id")
        base_url = os.getenv("GITLAB_BASE_URL")
        token = os.getenv("GIT_TOKEN")
        iid = obj_attrs.get("iid")
        try:
            post_comment_to_mr(base_url,project_id,token,iid, message)
        except Exception as e:
            logger.error(f"Failed to post initiation comment: {e}", exc_info=True)
        
        return {
            "flow_started": True,
            "project":        project.get("name"),
            "mr_iid":         iid,
            "merge_commit_sha": merge_commit,
            "target_branch":  target_branch,
        }

    logger.info(
        f"Skipping | is_merge_request={is_merge_request} | "
        f"is_merged_to_main={is_merged_to_main}"
    )
    return {
        "flow_started": False,
        "reason": f"state={state_val}, target={target_branch}",
    }
